# Generated by Django 4.1.2 on 2023-05-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_recommendedrestaurantsuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedrestaurantsuser',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
