# Generated by Django 4.1.5 on 2023-03-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedrestaurant',
            name='serchrest',
        ),
        migrations.RemoveField(
            model_name='searchedrestaurant',
            name='user_name',
        ),
        migrations.AddField(
            model_name='searchedrestaurant',
            name='restaurant_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='searchedrestaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
