# Generated by Django 4.1.2 on 2023-03-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_latitude_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='num_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
