# Generated by Django 4.1.2 on 2023-03-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurant_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restaurant_cuisine',
            new_name='RestaurantCuisine',
        ),
    ]
