# Generated by Django 4.1.2 on 2023-03-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_rename_restaurant_cuisine_restaurantcuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
