# Generated by Django 4.1.2 on 2023-03-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_image_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcuisine',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine', to='restaurant.cuisine'),
        ),
        migrations.AlterField(
            model_name='restaurantcuisine',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_cuisine', to='restaurant.restaurant'),
        ),
    ]
