# Generated by Django 4.1.2 on 2023-04-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_restaurantcuisine_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_restaurant', to='restaurant.restaurant'),
        ),
    ]
