# Generated by Django 4.1.2 on 2023-04-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_userprofile_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
