# Generated by Django 4.1.2 on 2023-04-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_ratings_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='user_profile',
        ),
    ]
