# Generated by Django 4.1.2 on 2023-04-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_remove_ratings_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='comment',
        ),
        migrations.AddField(
            model_name='ratings',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
