# Generated by Django 4.1.2 on 2023-04-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_remove_ratings_comment_ratings_body_ratings_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='num_bookings',
            field=models.IntegerField(default=10),
        ),
    ]
