# Generated by Django 4.1.2 on 2023-05-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_restaurant_num_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='u_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
