# Generated by Django 4.1.2 on 2023-05-01 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0017_ratings_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='user_i',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
