# Generated by Django 4.1.2 on 2023-05-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_ratings_user_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='user_i',
        ),
    ]
