# Generated by Django 4.1.2 on 2023-05-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_remove_ratings_user_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='u_id',
        ),
    ]
