# Generated by Django 4.1.2 on 2023-05-01 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_remove_ratings_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
