# Generated by Django 4.1.2 on 2023-05-03 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_rated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
