# Generated by Django 4.1.2 on 2023-05-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_rename_user_userprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
