# Generated by Django 4.1.2 on 2023-05-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_rename_user_id_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_rated',
            field=models.BooleanField(default=False),
        ),
    ]
