# Generated by Django 4.1.2 on 2023-05-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_userprofile_new_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='name', max_length=3000),
            preserve_default=False,
        ),
    ]
