# Generated by Django 4.2 on 2023-05-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_rename_name_image_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='created_at',
        ),
    ]
