# Generated by Django 4.2 on 2023-05-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_remove_ratings_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_rated_date',
        ),
    ]
