# Generated by Django 4.1.2 on 2023-03-18 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_cuisine_image_reservation_restaurant_and_more'),
        ('user', '0004_userprofile_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ownerRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_restaurant', to='restaurant.restaurant')),
            ],
        ),
    ]
